spring:
  datasource:
    url: jdbc:h2:mem:movieDB
    driverClassName: org.h2.Driver
    username: backbase
    password: backbase
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
    show-sql: false
    generate-ddl: false

omdb:
  baseUrl: http://www.omdbapi.com/
  apiKey: 9355ed78

server:
  error:
    include-message: always

resilience4j.circuitbreaker:
  instances:
    omdbApiCB:
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      waitDurationInOpenState: 30s